rpc:
  mainnet:
    uri: https://rpc.tzkt.io/mainnet
    timeout: 20
  delphinet:
    uri: https://rpc.tzkt.io/delphinet
    timeout: 20
  edo2net:
    uri: https://rpc.tzkt.io/edo2net
    timeout: 20
  falphanet:
    uri: https://rpc.tzkt.io/falphanet
    timeout: 20

tzkt:
  mainnet:
    uri: https://api.tzkt.io/v1/
    services_uri: https://services.tzkt.io/v1/
    base_uri: https://tzkt.io/
    timeout: 20
  delphinet:
    uri: https://api.delphi.tzkt.io/v1/
    services_uri: https://services.tzkt.io/delphinet/v1/
    base_uri: https://delphi.tzkt.io/
    timeout: 20
  edo2net:
    uri: https://api.edo2net.tzkt.io/v1/
    services_uri: https://services.tzkt.io/edo2net/v1/
    base_uri: https://edo2net.tzkt.io/
    timeout: 20

storage:
  uri:
    - http://127.0.0.1:9200
  timeout: 10

rabbitmq:
  uri: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@127.0.0.1:5672/"
  timeout: 10

db:
  conn_string: "host=127.0.0.1 port=5432 user=${POSTGRES_USER} dbname=${POSTGRES_DB} password=${POSTGRES_PASSWORD} sslmode=disable"
  timeout: 10

oauth:
  state: ${OAUTH_STATE_STRING}
  jwt:
    secret: ${JWT_SECRET_KEY}
    redirect_url: http://localhost:8080/welcome
  github:
    client_id: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}
    callback_url: http://localhost:14000/v1/oauth/github/callback
  gitlab:
    client_id: ${GITLAB_CLIENT_ID}
    secret: ${GITLAB_CLIENT_SECRET}
    callback_url: http://localhost:14000/v1/oauth/gitlab/callback

sentry:
  environment: development
  uri: ${SENTRY_DSN}
  front_uri: ${SENTRY_DSN_FRONT}
  debug: true

share_path: ${HOME}/.bcd

base_url: http://localhost:8080

ipfs:
  - https://ipfs.baking-bad.org
  - https://ipfs.io
  - https://dweb.link

domains:
  delphinet: KT1CR6vXJ1qeY4ALDQfUaLFi3FcJJZ8WDygo

api:
  project_name: api
  bind: "127.0.0.1:14000"
  swagger_host: "localhost:14000"
  cors_enabled: true
  oauth_enabled: true
  sentry_enabled: false
  seed_enabled: false
  frontend:
    ga_enabled: false
    mempool_enabled: true
    sandbox_mode: false
  networks:
    - mainnet
    - delphinet
    - edo2net
    - falphanet
  mq:
    publisher: true
    queues:
      operations:
        non_durable: true
        auto_deleted: true
        ttl_seconds: 10
      blocks:
        non_durable: true
        auto_deleted: true
        ttl_seconds: 10
  pinata:
    key: ${PINATA_KEY}
    secret_key: ${PINATA_SECRET_KEY}
    timeout_seconds: 10

compiler:
  project_name: compiler
  aws:
    bucket_name: bcd-contract-sources
    region: eu-central-1
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  sentry_enabled: false
  mq:
    publisher: true
    queues:
      compilations:

indexer:
  project_name: indexer
  sentry_enabled: false
  skip_delegator_blocks: true
  mq:
    publisher: true
  networks:
    mainnet:
      boost: tzkt
    delphinet:
      boost: tzkt
    edo2net:
      boost: tzkt
    falphanet:

metrics:
  project_name: metrics
  sentry_enabled: false
  cache_aliases_seconds: 30
  mq:
    publisher: false
    queues:
      operations:
      contracts:
      migrations:
      recalc:
      bigmapdiffs:
      projects:

scripts:
  aws:
    bucket_name: bcd-elastic-snapshots
    region: eu-central-1
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  networks:
    - mainnet
    - delphinet
    - edo2net
    - falphanet
  mq:
    publisher: true
